### ISSUE TITLE
max-width and ellipsis for ss-selection-item

### ISSUE THREAD

**Issue by kikonen** [kikonen/select_svelte#40]
```css
.ss-selection-item {
  max-width: 95%;
  overflow: hidden;
  text-overflow: ellipsis;
}
```
