### ISSUE TITLE
inline- form case broken

### ISSUE THREAD

**Issue by kikonen** [kikonen/select_svelte#43]
*due to* 
```css
@media (min-width: 576px)
.form-inline .form-control {
    display: inline-block;
    width: auto;
    vertical-align: middle;
}
```

*FIX*
```css
.ss-container {
  width: 100% !important;

  .ss-control {
    display: flex !important;
    width: 100% !important;
  }
}
```
